bws_shop_web_homepage:
    pattern:  /
    defaults: { _controller: BwsShopWebBundle:Articles:index }

bws_shop_web_search:
    pattern:  /search
    defaults: { _controller: BwsShopWebBundle:Articles:search }

bws_shop_web_add_to_basket:
    pattern: /basket/add/
    defaults: { _controller: BwsShopWebBundle:Basket:add }

bws_shop_web_list_basket:
    pattern: /basket.{_format}
    defaults: { _controller: BwsShopWebBundle:Basket:list, _format: html }

bws_shop_web_change_basket_position:
    pattern: /basket/change.{_format}
    defaults: { _controller: BwsShopWebBundle:Basket:change, _format: json }

bws_shop_web_authentication:
    pattern: /checkout/authentication
    defaults: { _controller: BwsShopWebBundle:Authentication:index }

bws_shop_web_unregistered:
    pattern: /checkout/unregistered
    defaults: { _controller: BwsShopWebBundle:UnregisteredCustomer:index }

bws_shop_web_submit_order:
    pattern: /checkout/order/submit
    defaults: { _controller: BwsShopWebBundle:Order:submit }

bws_shop_web_thanks:
    pattern: /checkout/thanks
    defaults: { _controller: BwsShopWebBundle:Order:thanks }