bws_shop_web_homepage:
    pattern:  /
    defaults: { _controller: BwsShopWebBundle:Article:index }

bws_shop_view_article:
    pattern:  /article/{id}
    defaults: { _controller: BwsShopWebBundle:Article:view }

bws_shop_web_search:
    pattern:  /search.{_format}
    defaults: { _controller: BwsShopWebBundle:Article:search, _format: html }

bws_shop_web_add_to_basket:
    pattern: /basket/add/
    defaults: { _controller: BwsShopWebBundle:Basket:add }

bws_shop_web_list_basket:
    pattern: /basket.{_format}
    defaults: { _controller: BwsShopWebBundle:Basket:list, _format: html }

bws_shop_web_change_basket_position:
    pattern: /basket/change.{_format}
    defaults: { _controller: BwsShopWebBundle:Basket:change, _format: json }

bws_shop_web_authentication:
    pattern: /checkout/authentication
    defaults: { _controller: BwsShopWebBundle:Authentication:index }

bws_shop_web_logout:
    pattern: /logout
    defaults: { _controller: BwsShopWebBundle:Authentication:logout }

bws_shop_web_registering:
    pattern: /checkout/registering
    defaults: { _controller: BwsShopWebBundle:UnregisteredCustomer:registering }

bws_shop_web_invoiceaddress_change:
    pattern: /invoiceaddress/change.{_format}
    defaults: { _controller: BwsShopWebBundle:InvoiceAddress:change, _format: json }

bws_shop_web_deliveryaddress_add:
    pattern: /deliveryaddress/add.{_format}
    defaults: { _controller: BwsShopWebBundle:DeliveryAddress:add, _format: json }

bws_shop_web_deliveryaddress_list:
    pattern: /deliveryaddress/list.{_format}
    defaults: { _controller: BwsShopWebBundle:DeliveryAddress:list, _format: json }

bws_shop_web_deliveryaddress_select:
    pattern: /deliveryaddress/select.{_format}
    defaults: { _controller: BwsShopWebBundle:DeliveryAddress:select, _format: json }

bws_shop_web_unregistered:
    pattern: /checkout/unregistered
    defaults: { _controller: BwsShopWebBundle:UnregisteredCustomer:index }

bws_shop_web_registered:
    pattern: /checkout/registered
    defaults: { _controller: BwsShopWebBundle:RegisteredCustomer:registered }

bws_shop_web_submit_order_registered:
    pattern: /checkout/order/submit
    defaults: { _controller: BwsShopWebBundle:Order:submitRegistered }

bws_shop_web_submit_order:
    pattern: /checkout/order/submit
    defaults: { _controller: BwsShopWebBundle:Order:submitUnregistered }

bws_shop_web_thanks:
    pattern: /checkout/thanks
    defaults: { _controller: BwsShopWebBundle:Order:thanks }