parameters:
    article.entity.class: Bws\DoctrineBundle\Entity\Article
    article.repository.class: Bws\DoctrineBundle\Entity\ArticleRepository
    basket.entity.class: Bws\DoctrineBundle\Entity\Basket
    basket.repository.class: Bws\DoctrineBundle\Entity\BasketRepository
    basket.position.entity.class: Bws\DoctrineBundle\Entity\BasketPosition
    basket.position.repository.class: Bws\DoctrineBundle\Entity\BasketPositionRepository
    invoiceaddress.entity.class: Bws\DoctrineBundle\Entity\InvoiceAddress
    invoiceaddress.repository.class: Bws\DoctrineBundle\Entity\InvoiceAddressRepository
    deliveryaddress.entity.class: Bws\DoctrineBundle\Entity\DeliveryAddress
    deliveryaddress.repository.class: Bws\DoctrineBundle\Entity\DeliveryAddressRepository
    order.entity.class: Bws\DoctrineBundle\Entity\Order
    order.repository.class: Bws\DoctrineBundle\Entity\OrderRepository

    interactor.add_to_basket.class: Bws\Interactor\AddToBasket
    interactor.view_basket.class: Bws\Interactor\ViewBasket
    interactor.change_basket.class: Bws\Interactor\ChangeBasket
    interactor.submit_order_unregistered.class: Bws\Interactor\SubmitOrderAsUnregisteredCustomer

services:
    article.repository:
        class: %article.repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - %article.entity.class%

    basket.repository:
        class: %basket.repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - %basket.entity.class%

    basket.position.repository:
        class: %basket.position.repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - %basket.position.entity.class%

    invoiceaddress.repository:
        class: %invoiceaddress.repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - %invoiceaddress.entity.class%

    deliveryaddress.repository:
        class: %deliveryaddress.repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - %deliveryaddress.entity.class%

    order.repository:
        class: %order.repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - %order.entity.class%

    interactor.add_to_basket:
        class: %interactor.add_to_basket.class%
        arguments:
            - @article.repository
            - @basket.position.repository
            - @basket.repository

    interactor.view_basket:
        class: %interactor.view_basket.class%
        arguments:
            - @basket.repository
            - @basket.position.repository

    interactor.change_basket:
        class: %interactor.change_basket.class%
        arguments:
            - @basket.position.repository
            - @basket.repository

    interactor.submit_order_unregistered:
        class: %interactor.submit_order_unregistered.class%
        arguments:
            - @invoiceaddress.repository
            - @deliveryaddress.repository
            - @basket.repository
            - @order.repository