parameters:
    article.entity.class: Bws\DoctrineBundle\Entity\Article
    article.repository.class: Bws\DoctrineBundle\Entity\ArticleRepository
    basket.entity.class: Bws\DoctrineBundle\Entity\Basket
    basket.repository.class: Bws\DoctrineBundle\Entity\BasketRepository
    basket.position.entity.class: Bws\DoctrineBundle\Entity\BasketPosition
    basket.position.repository.class: Bws\DoctrineBundle\Entity\BasketPositionRepository
    invoiceaddress.entity.class: Bws\DoctrineBundle\Entity\InvoiceAddress
    invoiceaddress.repository.class: Bws\DoctrineBundle\Entity\InvoiceAddressRepository
    deliveryaddress.entity.class: Bws\DoctrineBundle\Entity\DeliveryAddress
    deliveryaddress.repository.class: Bws\DoctrineBundle\Entity\DeliveryAddressRepository
    logisticpartner.entity.class: Bws\DoctrineBundle\Entity\LogisticPartner
    logisticpartner.repository.class: Bws\DoctrineBundle\Entity\LogisticPartnerRepository
    order.entity.class: Bws\DoctrineBundle\Entity\Order
    order.repository.class: Bws\DoctrineBundle\Entity\OrderRepository
    paymentmethod.entity.class: Bws\DoctrineBundle\Entity\PaymentMethod
    paymentmethod.repository.class: Bws\DoctrineBundle\Entity\PaymentMethodRepository
    interactor.add_to_basket.class: Bws\Interactor\AddToBasket
    interactor.view_basket.class: Bws\Interactor\ViewBasket
    interactor.change_basket.class: Bws\Interactor\ChangeBasket
    interactor.submit_order_unregistered.class: Bws\Interactor\SubmitOrderAsUnregisteredCustomer
    interactor.present_articles.class: Bws\Interactor\PresentArticles
    interactor.present_paymentmethods.class: Bws\Interactor\PresentPaymentMethods
    interactor.present_logisticpartners.class: Bws\Interactor\PresentLogisticPartners

services:
    article.repository:
        class: %article.repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - %article.entity.class%

    basket.repository:
        class: %basket.repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - %basket.entity.class%

    basket.position.repository:
        class: %basket.position.repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - %basket.position.entity.class%

    invoiceaddress.repository:
        class: %invoiceaddress.repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - %invoiceaddress.entity.class%

    deliveryaddress.repository:
        class: %deliveryaddress.repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - %deliveryaddress.entity.class%

    logisticpartner.repository:
        class: %logisticpartner.repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - %logisticpartner.entity.class%

    order.repository:
        class: %order.repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - %order.entity.class%

    paymentmethod.repository:
        class: %paymentmethod.repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - %paymentmethod.entity.class%

    interactor.add_to_basket:
        class: %interactor.add_to_basket.class%
        arguments:
            - @article.repository
            - @basket.position.repository
            - @basket.repository

    interactor.view_basket:
        class: %interactor.view_basket.class%
        arguments:
            - @basket.repository
            - @basket.position.repository

    interactor.change_basket:
        class: %interactor.change_basket.class%
        arguments:
            - @basket.position.repository
            - @basket.repository

    interactor.submit_order_unregistered:
        class: %interactor.submit_order_unregistered.class%
        arguments:
            - @invoiceaddress.repository
            - @deliveryaddress.repository
            - @basket.repository
            - @order.repository

    interactor.present_articles:
        class: %interactor.present_articles.class%
        arguments:
            - @article.repository

    interactor.present_logisticpartners:
        class: %interactor.present_logisticpartners.class%
        arguments:
            - @logisticpartner.repository

    interactor.present_paymentmethods:
        class: %interactor.present_paymentmethods.class%
        arguments:
            - @paymentmethod.repository