<?php

namespace Bws\DoctrineBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LogisticPartnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogisticPartnerRepository extends EntityRepository implements \Bws\Repository\LogisticPartnerRepository
{

}
