<?php

namespace Bws\DoctrineBundle\Entity;

use Bws\Entity\Order as BaseOrder;
use Doctrine\ORM\EntityRepository;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends EntityRepository implements \Bws\Repository\OrderRepository
{
    /**
     * @param BaseOrder $order
     */
    public function save(BaseOrder $order)
    {
        $this->getEntityManager()->persist($order);
        $this->getEntityManager()->flush();
    }

    /**
     * @return Order
     */
    public function factory()
    {
        return new Order();
    }
}
